version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  user-service:
    image: kbhatt23/user-service:0.0.1-SNAPSHOT
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB: kubernetes-db
      RDS_USER: user-kubernetes
      RDS_PASSWORD: kubernetespassword
    networks:
      - kubernetes-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_USER: user-kubernetes
      MYSQL_PASSWORD: kubernetespassword
      MYSQL_DATABASE: kubernetes-db
#    volumes:
#      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - kubernetes-network  
  
# Volumes
#volumes:
#  mysql-database-data-volume:

networks:
  kubernetes-network:  
  